version: '3.3'
services:
        prometheus:
                image: "prom/prometheus"
                ports: 
                        - "9090:9090"
                volumes: 
                        - /home/pi/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
